baseURL = 'initia.club'
languageCode = 'en-us'
title = 'initia'
theme = 'lightbi-hugo'
Paginate = 6

[Params] 
mainSections = ["members","members"]
dateFormat = "2 January 2023"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true 
summaryLength  = "9"
gcse = false
Lastmod = false
rss = false 
pagination = "10"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "Sragvee Satluri"
  website = "https://binovarghese.com/"
  email = "sample@gmail.com"
  facebook = "initia"
  instagram = "initia"
  youtube = "user/username" # or channel/channelname
  twitter = "initia"
  linkedin = "initia"
  github = "initia"
  #gitlab = "username"
  #bitbucket = "username"
  #reddit = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/#about"
    weight = 2

[[menu.main]]
    name = "Solutions"
    url = "/#solutions"
    weight = 3

[[menu.main]]
    name = "Join"
    url = "/#join"
    weight = 4



